(cl:in-package septentrio_gnss_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          BLOCK_HEADER-VAL
          BLOCK_HEADER
          MODE-VAL
          MODE
          ERROR-VAL
          ERROR
          COV_VNVN-VAL
          COV_VNVN
          COV_VEVE-VAL
          COV_VEVE
          COV_VUVU-VAL
          COV_VUVU
          COV_DTDT-VAL
          COV_DTDT
          COV_VNVE-VAL
          COV_VNVE
          COV_VNVU-VAL
          COV_VNVU
          COV_VNDT-VAL
          COV_VNDT
          COV_VEVU-VAL
          COV_VEVU
          COV_VEDT-VAL
          COV_VEDT
          COV_VUDT-VAL
          COV_VUDT
))