(cl:in-package septentrio_gnss_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          BLOCK_HEADER-VAL
          BLOCK_HEADER
          MODE-VAL
          MODE
          ERROR-VAL
          ERROR
          COV_LATLAT-VAL
          COV_LATLAT
          COV_LONLON-VAL
          COV_LONLON
          COV_HGTHGT-VAL
          COV_HGTHGT
          COV_BB-VAL
          COV_BB
          COV_LATLON-VAL
          COV_LATLON
          COV_LATHGT-VAL
          COV_LATHGT
          COV_LATB-VAL
          COV_LATB
          COV_LONHGT-VAL
          COV_LONHGT
          COV_LONB-VAL
          COV_LONB
          COV_HB-VAL
          COV_HB
))