(cl:in-package septentrio_gnss_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          BLOCK_HEADER-VAL
          BLOCK_HEADER
          MODE-VAL
          MODE
          ERROR-VAL
          ERROR
          COV_VXVX-VAL
          COV_VXVX
          COV_VYVY-VAL
          COV_VYVY
          COV_VZVZ-VAL
          COV_VZVZ
          COV_DTDT-VAL
          COV_DTDT
          COV_VXVY-VAL
          COV_VXVY
          COV_VXVZ-VAL
          COV_VXVZ
          COV_VXDT-VAL
          COV_VXDT
          COV_VYVZ-VAL
          COV_VYVZ
          COV_VYDT-VAL
          COV_VYDT
          COV_VZDT-VAL
          COV_VZDT
))