(cl:in-package septentrio_gnss_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          BLOCK_HEADER-VAL
          BLOCK_HEADER
          MODE-VAL
          MODE
          ERROR-VAL
          ERROR
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          UNDULATION-VAL
          UNDULATION
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          COG-VAL
          COG
          RX_CLK_BIAS-VAL
          RX_CLK_BIAS
          RX_CLK_DRIFT-VAL
          RX_CLK_DRIFT
          TIME_SYSTEM-VAL
          TIME_SYSTEM
          DATUM-VAL
          DATUM
          NR_SV-VAL
          NR_SV
          WA_CORR_INFO-VAL
          WA_CORR_INFO
          REFERENCE_ID-VAL
          REFERENCE_ID
          MEAN_CORR_AGE-VAL
          MEAN_CORR_AGE
          SIGNAL_INFO-VAL
          SIGNAL_INFO
          ALERT_FLAG-VAL
          ALERT_FLAG
          NR_BASES-VAL
          NR_BASES
          PPP_INFO-VAL
          PPP_INFO
          LATENCY-VAL
          LATENCY
          H_ACCURACY-VAL
          H_ACCURACY
          V_ACCURACY-VAL
          V_ACCURACY
          MISC-VAL
          MISC
))