(cl:in-package septentrio_gnss_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          BLOCK_HEADER-VAL
          BLOCK_HEADER
          GNSS_MODE-VAL
          GNSS_MODE
          ERROR-VAL
          ERROR
          INFO-VAL
          INFO
          GNSS_AGE-VAL
          GNSS_AGE
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          HEIGHT-VAL
          HEIGHT
          UNDULATION-VAL
          UNDULATION
          ACCURACY-VAL
          ACCURACY
          LATENCY-VAL
          LATENCY
          DATUM-VAL
          DATUM
          SB_LIST-VAL
          SB_LIST
          LATITUDE_STD_DEV-VAL
          LATITUDE_STD_DEV
          LONGITUDE_STD_DEV-VAL
          LONGITUDE_STD_DEV
          HEIGHT_STD_DEV-VAL
          HEIGHT_STD_DEV
          LATITUDE_LONGITUDE_COV-VAL
          LATITUDE_LONGITUDE_COV
          LATITUDE_HEIGHT_COV-VAL
          LATITUDE_HEIGHT_COV
          LONGITUDE_HEIGHT_COV-VAL
          LONGITUDE_HEIGHT_COV
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          HEADING_STD_DEV-VAL
          HEADING_STD_DEV
          PITCH_STD_DEV-VAL
          PITCH_STD_DEV
          ROLL_STD_DEV-VAL
          ROLL_STD_DEV
          HEADING_PITCH_COV-VAL
          HEADING_PITCH_COV
          HEADING_ROLL_COV-VAL
          HEADING_ROLL_COV
          PITCH_ROLL_COV-VAL
          PITCH_ROLL_COV
          VE-VAL
          VE
          VN-VAL
          VN
          VU-VAL
          VU
          VE_STD_DEV-VAL
          VE_STD_DEV
          VN_STD_DEV-VAL
          VN_STD_DEV
          VU_STD_DEV-VAL
          VU_STD_DEV
          VE_VN_COV-VAL
          VE_VN_COV
          VE_VU_COV-VAL
          VE_VU_COV
          VN_VU_COV-VAL
          VN_VU_COV
))