(cl:in-package septentrio_gnss_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          BLOCK_HEADER-VAL
          BLOCK_HEADER
          N-VAL
          N
          SB_LENGTH-VAL
          SB_LENGTH
          SOURCE-VAL
          SOURCE
          SENSOR_MODEL-VAL
          SENSOR_MODEL
          TYPE-VAL
          TYPE
          OBS_INFO-VAL
          OBS_INFO
          ACCELERATION_X-VAL
          ACCELERATION_X
          ACCELERATION_Y-VAL
          ACCELERATION_Y
          ACCELERATION_Z-VAL
          ACCELERATION_Z
          ANGULAR_RATE_X-VAL
          ANGULAR_RATE_X
          ANGULAR_RATE_Y-VAL
          ANGULAR_RATE_Y
          ANGULAR_RATE_Z-VAL
          ANGULAR_RATE_Z
          VELOCITY_X-VAL
          VELOCITY_X
          VELOCITY_Y-VAL
          VELOCITY_Y
          VELOCITY_Z-VAL
          VELOCITY_Z
          STD_DEV_X-VAL
          STD_DEV_X
          STD_DEV_Y-VAL
          STD_DEV_Y
          STD_DEV_Z-VAL
          STD_DEV_Z
          SENSOR_TEMPERATURE-VAL
          SENSOR_TEMPERATURE
          ZERO_VELOCITY_FLAG-VAL
          ZERO_VELOCITY_FLAG
))