(cl:in-package septentrio_gnss_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          BLOCK_HEADER-VAL
          BLOCK_HEADER
          MODE-VAL
          MODE
          ERROR-VAL
          ERROR
          COV_XX-VAL
          COV_XX
          COV_YY-VAL
          COV_YY
          COV_ZZ-VAL
          COV_ZZ
          COV_BB-VAL
          COV_BB
          COV_XY-VAL
          COV_XY
          COV_XZ-VAL
          COV_XZ
          COV_XB-VAL
          COV_XB
          COV_YZ-VAL
          COV_YZ
          COV_YB-VAL
          COV_YB
          COV_ZB-VAL
          COV_ZB
))