(cl:in-package septentrio_gnss_driver-msg)
(cl:export '(HEADER-VAL
          HEADER
          BLOCK_HEADER-VAL
          BLOCK_HEADER
          GNSS_MODE-VAL
          GNSS_MODE
          ERROR-VAL
          ERROR
          INFO-VAL
          INFO
          GNSS_AGE-VAL
          GNSS_AGE
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          ACCURACY-VAL
          ACCURACY
          LATENCY-VAL
          LATENCY
          DATUM-VAL
          DATUM
          SB_LIST-VAL
          SB_LIST
          X_STD_DEV-VAL
          X_STD_DEV
          Y_STD_DEV-VAL
          Y_STD_DEV
          Z_STD_DEV-VAL
          Z_STD_DEV
          XY_COV-VAL
          XY_COV
          XZ_COV-VAL
          XZ_COV
          YZ_COV-VAL
          YZ_COV
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          HEADING_STD_DEV-VAL
          HEADING_STD_DEV
          PITCH_STD_DEV-VAL
          PITCH_STD_DEV
          ROLL_STD_DEV-VAL
          ROLL_STD_DEV
          HEADING_PITCH_COV-VAL
          HEADING_PITCH_COV
          HEADING_ROLL_COV-VAL
          HEADING_ROLL_COV
          PITCH_ROLL_COV-VAL
          PITCH_ROLL_COV
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          VX_STD_DEV-VAL
          VX_STD_DEV
          VY_STD_DEV-VAL
          VY_STD_DEV
          VZ_STD_DEV-VAL
          VZ_STD_DEV
          VX_VY_COV-VAL
          VX_VY_COV
          VX_VZ_COV-VAL
          VX_VZ_COV
          VY_VZ_COV-VAL
          VY_VZ_COV
))