(cl:in-package septentrio_gnss_driver-msg)
(cl:export '(NR_SV-VAL
          NR_SV
          ERROR-VAL
          ERROR
          MODE-VAL
          MODE
          MISC-VAL
          MISC
          DELTA_X-VAL
          DELTA_X
          DELTA_Y-VAL
          DELTA_Y
          DELTA_Z-VAL
          DELTA_Z
          DELTA_VX-VAL
          DELTA_VX
          DELTA_VY-VAL
          DELTA_VY
          DELTA_VZ-VAL
          DELTA_VZ
          AZIMUTH-VAL
          AZIMUTH
          ELEVATION-VAL
          ELEVATION
          REFERENCE_ID-VAL
          REFERENCE_ID
          CORR_AGE-VAL
          CORR_AGE
          SIGNAL_INFO-VAL
          SIGNAL_INFO
))