(cl:in-package septentrio_gnss_driver-msg)
(cl:export '(NR_SV-VAL
          NR_SV
          ERROR-VAL
          ERROR
          MODE-VAL
          MODE
          MISC-VAL
          MISC
          DELTA_EAST-VAL
          DELTA_EAST
          DELTA_NORTH-VAL
          DELTA_NORTH
          DELTA_UP-VAL
          DELTA_UP
          DELTA_VE-VAL
          DELTA_VE
          DELTA_VN-VAL
          DELTA_VN
          DELTA_VU-VAL
          DELTA_VU
          AZIMUTH-VAL
          AZIMUTH
          ELEVATION-VAL
          ELEVATION
          REFERENCE_ID-VAL
          REFERENCE_ID
          CORR_AGE-VAL
          CORR_AGE
          SIGNAL_INFO-VAL
          SIGNAL_INFO
))