// Generated by gencpp from file septentrio_gnss_driver/INSNavCart.msg
// DO NOT EDIT!


#ifndef SEPTENTRIO_GNSS_DRIVER_MESSAGE_INSNAVCART_H
#define SEPTENTRIO_GNSS_DRIVER_MESSAGE_INSNAVCART_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <septentrio_gnss_driver/BlockHeader.h>

namespace septentrio_gnss_driver
{
template <class ContainerAllocator>
struct INSNavCart_
{
  typedef INSNavCart_<ContainerAllocator> Type;

  INSNavCart_()
    : header()
    , block_header()
    , gnss_mode(0)
    , error(0)
    , info(0)
    , gnss_age(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , accuracy(0)
    , latency(0)
    , datum(0)
    , sb_list(0)
    , x_std_dev(0.0)
    , y_std_dev(0.0)
    , z_std_dev(0.0)
    , xy_cov(0.0)
    , xz_cov(0.0)
    , yz_cov(0.0)
    , heading(0.0)
    , pitch(0.0)
    , roll(0.0)
    , heading_std_dev(0.0)
    , pitch_std_dev(0.0)
    , roll_std_dev(0.0)
    , heading_pitch_cov(0.0)
    , heading_roll_cov(0.0)
    , pitch_roll_cov(0.0)
    , vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , vx_std_dev(0.0)
    , vy_std_dev(0.0)
    , vz_std_dev(0.0)
    , vx_vy_cov(0.0)
    , vx_vz_cov(0.0)
    , vy_vz_cov(0.0)  {
    }
  INSNavCart_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , block_header(_alloc)
    , gnss_mode(0)
    , error(0)
    , info(0)
    , gnss_age(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , accuracy(0)
    , latency(0)
    , datum(0)
    , sb_list(0)
    , x_std_dev(0.0)
    , y_std_dev(0.0)
    , z_std_dev(0.0)
    , xy_cov(0.0)
    , xz_cov(0.0)
    , yz_cov(0.0)
    , heading(0.0)
    , pitch(0.0)
    , roll(0.0)
    , heading_std_dev(0.0)
    , pitch_std_dev(0.0)
    , roll_std_dev(0.0)
    , heading_pitch_cov(0.0)
    , heading_roll_cov(0.0)
    , pitch_roll_cov(0.0)
    , vx(0.0)
    , vy(0.0)
    , vz(0.0)
    , vx_std_dev(0.0)
    , vy_std_dev(0.0)
    , vz_std_dev(0.0)
    , vx_vy_cov(0.0)
    , vx_vz_cov(0.0)
    , vy_vz_cov(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::septentrio_gnss_driver::BlockHeader_<ContainerAllocator>  _block_header_type;
  _block_header_type block_header;

   typedef uint8_t _gnss_mode_type;
  _gnss_mode_type gnss_mode;

   typedef uint8_t _error_type;
  _error_type error;

   typedef uint16_t _info_type;
  _info_type info;

   typedef uint16_t _gnss_age_type;
  _gnss_age_type gnss_age;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef uint16_t _accuracy_type;
  _accuracy_type accuracy;

   typedef uint16_t _latency_type;
  _latency_type latency;

   typedef uint8_t _datum_type;
  _datum_type datum;

   typedef uint16_t _sb_list_type;
  _sb_list_type sb_list;

   typedef float _x_std_dev_type;
  _x_std_dev_type x_std_dev;

   typedef float _y_std_dev_type;
  _y_std_dev_type y_std_dev;

   typedef float _z_std_dev_type;
  _z_std_dev_type z_std_dev;

   typedef float _xy_cov_type;
  _xy_cov_type xy_cov;

   typedef float _xz_cov_type;
  _xz_cov_type xz_cov;

   typedef float _yz_cov_type;
  _yz_cov_type yz_cov;

   typedef float _heading_type;
  _heading_type heading;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _heading_std_dev_type;
  _heading_std_dev_type heading_std_dev;

   typedef float _pitch_std_dev_type;
  _pitch_std_dev_type pitch_std_dev;

   typedef float _roll_std_dev_type;
  _roll_std_dev_type roll_std_dev;

   typedef float _heading_pitch_cov_type;
  _heading_pitch_cov_type heading_pitch_cov;

   typedef float _heading_roll_cov_type;
  _heading_roll_cov_type heading_roll_cov;

   typedef float _pitch_roll_cov_type;
  _pitch_roll_cov_type pitch_roll_cov;

   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;

   typedef float _vz_type;
  _vz_type vz;

   typedef float _vx_std_dev_type;
  _vx_std_dev_type vx_std_dev;

   typedef float _vy_std_dev_type;
  _vy_std_dev_type vy_std_dev;

   typedef float _vz_std_dev_type;
  _vz_std_dev_type vz_std_dev;

   typedef float _vx_vy_cov_type;
  _vx_vy_cov_type vx_vy_cov;

   typedef float _vx_vz_cov_type;
  _vx_vz_cov_type vx_vz_cov;

   typedef float _vy_vz_cov_type;
  _vy_vz_cov_type vy_vz_cov;





  typedef boost::shared_ptr< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> const> ConstPtr;

}; // struct INSNavCart_

typedef ::septentrio_gnss_driver::INSNavCart_<std::allocator<void> > INSNavCart;

typedef boost::shared_ptr< ::septentrio_gnss_driver::INSNavCart > INSNavCartPtr;
typedef boost::shared_ptr< ::septentrio_gnss_driver::INSNavCart const> INSNavCartConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator1> & lhs, const ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.block_header == rhs.block_header &&
    lhs.gnss_mode == rhs.gnss_mode &&
    lhs.error == rhs.error &&
    lhs.info == rhs.info &&
    lhs.gnss_age == rhs.gnss_age &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.accuracy == rhs.accuracy &&
    lhs.latency == rhs.latency &&
    lhs.datum == rhs.datum &&
    lhs.sb_list == rhs.sb_list &&
    lhs.x_std_dev == rhs.x_std_dev &&
    lhs.y_std_dev == rhs.y_std_dev &&
    lhs.z_std_dev == rhs.z_std_dev &&
    lhs.xy_cov == rhs.xy_cov &&
    lhs.xz_cov == rhs.xz_cov &&
    lhs.yz_cov == rhs.yz_cov &&
    lhs.heading == rhs.heading &&
    lhs.pitch == rhs.pitch &&
    lhs.roll == rhs.roll &&
    lhs.heading_std_dev == rhs.heading_std_dev &&
    lhs.pitch_std_dev == rhs.pitch_std_dev &&
    lhs.roll_std_dev == rhs.roll_std_dev &&
    lhs.heading_pitch_cov == rhs.heading_pitch_cov &&
    lhs.heading_roll_cov == rhs.heading_roll_cov &&
    lhs.pitch_roll_cov == rhs.pitch_roll_cov &&
    lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.vz == rhs.vz &&
    lhs.vx_std_dev == rhs.vx_std_dev &&
    lhs.vy_std_dev == rhs.vy_std_dev &&
    lhs.vz_std_dev == rhs.vz_std_dev &&
    lhs.vx_vy_cov == rhs.vx_vy_cov &&
    lhs.vx_vz_cov == rhs.vx_vz_cov &&
    lhs.vy_vz_cov == rhs.vy_vz_cov;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator1> & lhs, const ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace septentrio_gnss_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebb1a1e03ea3fac47ad5f19264160123";
  }

  static const char* value(const ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xebb1a1e03ea3fac4ULL;
  static const uint64_t static_value2 = 0x7ad5f19264160123ULL;
};

template<class ContainerAllocator>
struct DataType< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "septentrio_gnss_driver/INSNavCart";
  }

  static const char* value(const ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# INSNavCart block \n"
"# Block_Number 4225\n"
"\n"
"std_msgs/Header header\n"
"\n"
"# SBF block header including time header\n"
"BlockHeader block_header\n"
"\n"
"uint8       gnss_mode\n"
"uint8       error\n"
"uint16      info\n"
"uint16      gnss_age # 0.01 s\n"
"float64     x        # m\n"
"float64     y        # m\n"
"float64     z        # m\n"
"uint16      accuracy # 0.01 m\n"
"uint16      latency  # 0.1 ms\n"
"uint8       datum    \n"
"#uint8       reserved\n"
"uint16      sb_list\n"
"\n"
"# INSNavCartPosStdDev sub-block definition:\n"
"# If the Position StdDev field is 1 then this sub block is available:\n"
"float32     x_std_dev # m\n"
"float32     y_std_dev # m\n"
"float32     z_std_dev # m\n"
"\n"
"# INSNavCartPosCov sub-block definition:\n"
"# If the Position Cov field is 1 then this sub block is available:\n"
"float32     xy_cov # m^2\n"
"float32     xz_cov # m^2\n"
"float32     yz_cov # m^2\n"
"\n"
"# INSNavCartAtt sub-block definition:\n"
"# If the Attitude field is 1 then this sub block is available:\n"
"float32     heading # deg\n"
"float32     pitch   # deg\n"
"float32     roll    # deg\n"
"\n"
"# INSNavCartAttStdDev sub-block definition:\n"
"# If the Attitude StdDev field is 1 then this sub block is available:\n"
"float32     heading_std_dev # deg\n"
"float32     pitch_std_dev   # deg\n"
"float32     roll_std_dev    # deg\n"
"\n"
"# INSNavCartAttCov sub-block definition:\n"
"# If the Attitude Cov field is 1 then this sub block is available:\n"
"float32     heading_pitch_cov # deg^2\n"
"float32     heading_roll_cov  # deg^2\n"
"float32     pitch_roll_cov    # deg^2\n"
"\n"
"# INSNavCartVel sub-block definition:\n"
"# If the Velocity field is 1 then this sub block is available:\n"
"float32     vx # m/s\n"
"float32     vy # m/S\n"
"float32     vz # m/s\n"
"\n"
"# INSNavCartVelStdDev sub-block definition:\n"
"# If the Velocity StdDev field is 1 then this sub block is available:\n"
"float32     vx_std_dev # m/s\n"
"float32     vy_std_dev # m/s\n"
"float32     vz_std_dev # m/s\n"
"\n"
"# INSNavCartVelCov sub-block definition:\n"
"# If the Velocity Cov field is 1 then this sub block is available:\n"
"float32     vx_vy_cov # m^2/s^2\n"
"float32     vx_vz_cov # m^2/s^2\n"
"float32     vy_vz_cov # m^2/s^2\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: septentrio_gnss_driver/BlockHeader\n"
"# Blockheader including time header for all ROS messages that publish SBF blocks\n"
"\n"
"uint8     sync_1\n"
"uint8     sync_2\n"
"uint16    crc\n"
"uint16    id\n"
"uint8     revision\n"
"uint16    length\n"
"\n"
"uint32    tow # ms since week start\n"
"uint16    wnc # weeks since Jan 06, 1980 at 00:00:00 UTC     \n"
;
  }

  static const char* value(const ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.block_header);
      stream.next(m.gnss_mode);
      stream.next(m.error);
      stream.next(m.info);
      stream.next(m.gnss_age);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.accuracy);
      stream.next(m.latency);
      stream.next(m.datum);
      stream.next(m.sb_list);
      stream.next(m.x_std_dev);
      stream.next(m.y_std_dev);
      stream.next(m.z_std_dev);
      stream.next(m.xy_cov);
      stream.next(m.xz_cov);
      stream.next(m.yz_cov);
      stream.next(m.heading);
      stream.next(m.pitch);
      stream.next(m.roll);
      stream.next(m.heading_std_dev);
      stream.next(m.pitch_std_dev);
      stream.next(m.roll_std_dev);
      stream.next(m.heading_pitch_cov);
      stream.next(m.heading_roll_cov);
      stream.next(m.pitch_roll_cov);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
      stream.next(m.vx_std_dev);
      stream.next(m.vy_std_dev);
      stream.next(m.vz_std_dev);
      stream.next(m.vx_vy_cov);
      stream.next(m.vx_vz_cov);
      stream.next(m.vy_vz_cov);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct INSNavCart_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::septentrio_gnss_driver::INSNavCart_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "block_header: ";
    s << std::endl;
    Printer< ::septentrio_gnss_driver::BlockHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.block_header);
    s << indent << "gnss_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gnss_mode);
    s << indent << "error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error);
    s << indent << "info: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.info);
    s << indent << "gnss_age: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.gnss_age);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "accuracy: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.accuracy);
    s << indent << "latency: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.latency);
    s << indent << "datum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.datum);
    s << indent << "sb_list: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sb_list);
    s << indent << "x_std_dev: ";
    Printer<float>::stream(s, indent + "  ", v.x_std_dev);
    s << indent << "y_std_dev: ";
    Printer<float>::stream(s, indent + "  ", v.y_std_dev);
    s << indent << "z_std_dev: ";
    Printer<float>::stream(s, indent + "  ", v.z_std_dev);
    s << indent << "xy_cov: ";
    Printer<float>::stream(s, indent + "  ", v.xy_cov);
    s << indent << "xz_cov: ";
    Printer<float>::stream(s, indent + "  ", v.xz_cov);
    s << indent << "yz_cov: ";
    Printer<float>::stream(s, indent + "  ", v.yz_cov);
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "heading_std_dev: ";
    Printer<float>::stream(s, indent + "  ", v.heading_std_dev);
    s << indent << "pitch_std_dev: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_std_dev);
    s << indent << "roll_std_dev: ";
    Printer<float>::stream(s, indent + "  ", v.roll_std_dev);
    s << indent << "heading_pitch_cov: ";
    Printer<float>::stream(s, indent + "  ", v.heading_pitch_cov);
    s << indent << "heading_roll_cov: ";
    Printer<float>::stream(s, indent + "  ", v.heading_roll_cov);
    s << indent << "pitch_roll_cov: ";
    Printer<float>::stream(s, indent + "  ", v.pitch_roll_cov);
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<float>::stream(s, indent + "  ", v.vz);
    s << indent << "vx_std_dev: ";
    Printer<float>::stream(s, indent + "  ", v.vx_std_dev);
    s << indent << "vy_std_dev: ";
    Printer<float>::stream(s, indent + "  ", v.vy_std_dev);
    s << indent << "vz_std_dev: ";
    Printer<float>::stream(s, indent + "  ", v.vz_std_dev);
    s << indent << "vx_vy_cov: ";
    Printer<float>::stream(s, indent + "  ", v.vx_vy_cov);
    s << indent << "vx_vz_cov: ";
    Printer<float>::stream(s, indent + "  ", v.vx_vz_cov);
    s << indent << "vy_vz_cov: ";
    Printer<float>::stream(s, indent + "  ", v.vy_vz_cov);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEPTENTRIO_GNSS_DRIVER_MESSAGE_INSNAVCART_H
