// Generated by gencpp from file septentrio_gnss_driver/PosCovGeodetic.msg
// DO NOT EDIT!


#ifndef SEPTENTRIO_GNSS_DRIVER_MESSAGE_POSCOVGEODETIC_H
#define SEPTENTRIO_GNSS_DRIVER_MESSAGE_POSCOVGEODETIC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <septentrio_gnss_driver/BlockHeader.h>

namespace septentrio_gnss_driver
{
template <class ContainerAllocator>
struct PosCovGeodetic_
{
  typedef PosCovGeodetic_<ContainerAllocator> Type;

  PosCovGeodetic_()
    : header()
    , block_header()
    , mode(0)
    , error(0)
    , cov_latlat(0.0)
    , cov_lonlon(0.0)
    , cov_hgthgt(0.0)
    , cov_bb(0.0)
    , cov_latlon(0.0)
    , cov_lathgt(0.0)
    , cov_latb(0.0)
    , cov_lonhgt(0.0)
    , cov_lonb(0.0)
    , cov_hb(0.0)  {
    }
  PosCovGeodetic_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , block_header(_alloc)
    , mode(0)
    , error(0)
    , cov_latlat(0.0)
    , cov_lonlon(0.0)
    , cov_hgthgt(0.0)
    , cov_bb(0.0)
    , cov_latlon(0.0)
    , cov_lathgt(0.0)
    , cov_latb(0.0)
    , cov_lonhgt(0.0)
    , cov_lonb(0.0)
    , cov_hb(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::septentrio_gnss_driver::BlockHeader_<ContainerAllocator>  _block_header_type;
  _block_header_type block_header;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _error_type;
  _error_type error;

   typedef float _cov_latlat_type;
  _cov_latlat_type cov_latlat;

   typedef float _cov_lonlon_type;
  _cov_lonlon_type cov_lonlon;

   typedef float _cov_hgthgt_type;
  _cov_hgthgt_type cov_hgthgt;

   typedef float _cov_bb_type;
  _cov_bb_type cov_bb;

   typedef float _cov_latlon_type;
  _cov_latlon_type cov_latlon;

   typedef float _cov_lathgt_type;
  _cov_lathgt_type cov_lathgt;

   typedef float _cov_latb_type;
  _cov_latb_type cov_latb;

   typedef float _cov_lonhgt_type;
  _cov_lonhgt_type cov_lonhgt;

   typedef float _cov_lonb_type;
  _cov_lonb_type cov_lonb;

   typedef float _cov_hb_type;
  _cov_hb_type cov_hb;





  typedef boost::shared_ptr< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> const> ConstPtr;

}; // struct PosCovGeodetic_

typedef ::septentrio_gnss_driver::PosCovGeodetic_<std::allocator<void> > PosCovGeodetic;

typedef boost::shared_ptr< ::septentrio_gnss_driver::PosCovGeodetic > PosCovGeodeticPtr;
typedef boost::shared_ptr< ::septentrio_gnss_driver::PosCovGeodetic const> PosCovGeodeticConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator1> & lhs, const ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.block_header == rhs.block_header &&
    lhs.mode == rhs.mode &&
    lhs.error == rhs.error &&
    lhs.cov_latlat == rhs.cov_latlat &&
    lhs.cov_lonlon == rhs.cov_lonlon &&
    lhs.cov_hgthgt == rhs.cov_hgthgt &&
    lhs.cov_bb == rhs.cov_bb &&
    lhs.cov_latlon == rhs.cov_latlon &&
    lhs.cov_lathgt == rhs.cov_lathgt &&
    lhs.cov_latb == rhs.cov_latb &&
    lhs.cov_lonhgt == rhs.cov_lonhgt &&
    lhs.cov_lonb == rhs.cov_lonb &&
    lhs.cov_hb == rhs.cov_hb;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator1> & lhs, const ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace septentrio_gnss_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5a0ad571ba33ff67cc97dcff03d6b87";
  }

  static const char* value(const ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5a0ad571ba33ff6ULL;
  static const uint64_t static_value2 = 0x7cc97dcff03d6b87ULL;
};

template<class ContainerAllocator>
struct DataType< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "septentrio_gnss_driver/PosCovGeodetic";
  }

  static const char* value(const ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# PVTGeodetic block\n"
"# ROS message header\n"
"std_msgs/Header header\n"
"\n"
"# SBF block header including time header\n"
"BlockHeader  block_header   \n"
"\n"
"uint8        mode\n"
"uint8        error        \n"
"float32      cov_latlat # m^2\n"
"float32      cov_lonlon # m^2\n"
"float32      cov_hgthgt # m^2\n"
"float32      cov_bb     # m^2\n"
"float32      cov_latlon # m^2\n"
"float32      cov_lathgt # m^2\n"
"float32      cov_latb   # m^2\n"
"float32      cov_lonhgt # m^2\n"
"float32      cov_lonb   # m^2\n"
"float32      cov_hb     # m^2\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: septentrio_gnss_driver/BlockHeader\n"
"# Blockheader including time header for all ROS messages that publish SBF blocks\n"
"\n"
"uint8     sync_1\n"
"uint8     sync_2\n"
"uint16    crc\n"
"uint16    id\n"
"uint8     revision\n"
"uint16    length\n"
"\n"
"uint32    tow # ms since week start\n"
"uint16    wnc # weeks since Jan 06, 1980 at 00:00:00 UTC     \n"
;
  }

  static const char* value(const ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.block_header);
      stream.next(m.mode);
      stream.next(m.error);
      stream.next(m.cov_latlat);
      stream.next(m.cov_lonlon);
      stream.next(m.cov_hgthgt);
      stream.next(m.cov_bb);
      stream.next(m.cov_latlon);
      stream.next(m.cov_lathgt);
      stream.next(m.cov_latb);
      stream.next(m.cov_lonhgt);
      stream.next(m.cov_lonb);
      stream.next(m.cov_hb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PosCovGeodetic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::septentrio_gnss_driver::PosCovGeodetic_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "block_header: ";
    s << std::endl;
    Printer< ::septentrio_gnss_driver::BlockHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.block_header);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error);
    s << indent << "cov_latlat: ";
    Printer<float>::stream(s, indent + "  ", v.cov_latlat);
    s << indent << "cov_lonlon: ";
    Printer<float>::stream(s, indent + "  ", v.cov_lonlon);
    s << indent << "cov_hgthgt: ";
    Printer<float>::stream(s, indent + "  ", v.cov_hgthgt);
    s << indent << "cov_bb: ";
    Printer<float>::stream(s, indent + "  ", v.cov_bb);
    s << indent << "cov_latlon: ";
    Printer<float>::stream(s, indent + "  ", v.cov_latlon);
    s << indent << "cov_lathgt: ";
    Printer<float>::stream(s, indent + "  ", v.cov_lathgt);
    s << indent << "cov_latb: ";
    Printer<float>::stream(s, indent + "  ", v.cov_latb);
    s << indent << "cov_lonhgt: ";
    Printer<float>::stream(s, indent + "  ", v.cov_lonhgt);
    s << indent << "cov_lonb: ";
    Printer<float>::stream(s, indent + "  ", v.cov_lonb);
    s << indent << "cov_hb: ";
    Printer<float>::stream(s, indent + "  ", v.cov_hb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEPTENTRIO_GNSS_DRIVER_MESSAGE_POSCOVGEODETIC_H
