// Generated by gencpp from file septentrio_gnss_driver/RFStatus.msg
// DO NOT EDIT!


#ifndef SEPTENTRIO_GNSS_DRIVER_MESSAGE_RFSTATUS_H
#define SEPTENTRIO_GNSS_DRIVER_MESSAGE_RFSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <septentrio_gnss_driver/BlockHeader.h>
#include <septentrio_gnss_driver/RFBand.h>

namespace septentrio_gnss_driver
{
template <class ContainerAllocator>
struct RFStatus_
{
  typedef RFStatus_<ContainerAllocator> Type;

  RFStatus_()
    : header()
    , block_header()
    , n(0)
    , sb_length(0)
    , flags(0)
    , rfband()  {
    }
  RFStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , block_header(_alloc)
    , n(0)
    , sb_length(0)
    , flags(0)
    , rfband(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::septentrio_gnss_driver::BlockHeader_<ContainerAllocator>  _block_header_type;
  _block_header_type block_header;

   typedef uint8_t _n_type;
  _n_type n;

   typedef uint8_t _sb_length_type;
  _sb_length_type sb_length;

   typedef uint8_t _flags_type;
  _flags_type flags;

   typedef std::vector< ::septentrio_gnss_driver::RFBand_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::septentrio_gnss_driver::RFBand_<ContainerAllocator> >> _rfband_type;
  _rfband_type rfband;





  typedef boost::shared_ptr< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RFStatus_

typedef ::septentrio_gnss_driver::RFStatus_<std::allocator<void> > RFStatus;

typedef boost::shared_ptr< ::septentrio_gnss_driver::RFStatus > RFStatusPtr;
typedef boost::shared_ptr< ::septentrio_gnss_driver::RFStatus const> RFStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::septentrio_gnss_driver::RFStatus_<ContainerAllocator1> & lhs, const ::septentrio_gnss_driver::RFStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.block_header == rhs.block_header &&
    lhs.n == rhs.n &&
    lhs.sb_length == rhs.sb_length &&
    lhs.flags == rhs.flags &&
    lhs.rfband == rhs.rfband;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::septentrio_gnss_driver::RFStatus_<ContainerAllocator1> & lhs, const ::septentrio_gnss_driver::RFStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace septentrio_gnss_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6223e703baf4d3da19e391be72a94d34";
  }

  static const char* value(const ::septentrio_gnss_driver::RFStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6223e703baf4d3daULL;
  static const uint64_t static_value2 = 0x19e391be72a94d34ULL;
};

template<class ContainerAllocator>
struct DataType< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "septentrio_gnss_driver/RFStatus";
  }

  static const char* value(const ::septentrio_gnss_driver::RFStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# RFStatus block\n"
"# ROS message header\n"
"std_msgs/Header header\n"
"\n"
"# SBF block header including time header\n"
"BlockHeader  block_header\n"
"\n"
"uint8    n\n"
"uint8    sb_length\n"
"uint8    flags\n"
"RFBand[] rfband\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: septentrio_gnss_driver/BlockHeader\n"
"# Blockheader including time header for all ROS messages that publish SBF blocks\n"
"\n"
"uint8     sync_1\n"
"uint8     sync_2\n"
"uint16    crc\n"
"uint16    id\n"
"uint8     revision\n"
"uint16    length\n"
"\n"
"uint32    tow # ms since week start\n"
"uint16    wnc # weeks since Jan 06, 1980 at 00:00:00 UTC     \n"
"================================================================================\n"
"MSG: septentrio_gnss_driver/RFBand\n"
"# RFband block\n"
"\n"
"uint32 frequency # Hz\n"
"uint16 bandwidth # kHz\n"
"uint8  info\n"
;
  }

  static const char* value(const ::septentrio_gnss_driver::RFStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.block_header);
      stream.next(m.n);
      stream.next(m.sb_length);
      stream.next(m.flags);
      stream.next(m.rfband);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RFStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::septentrio_gnss_driver::RFStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::septentrio_gnss_driver::RFStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "block_header: ";
    s << std::endl;
    Printer< ::septentrio_gnss_driver::BlockHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.block_header);
    s << indent << "n: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.n);
    s << indent << "sb_length: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sb_length);
    s << indent << "flags: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flags);
    s << indent << "rfband[]" << std::endl;
    for (size_t i = 0; i < v.rfband.size(); ++i)
    {
      s << indent << "  rfband[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::septentrio_gnss_driver::RFBand_<ContainerAllocator> >::stream(s, indent + "    ", v.rfband[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEPTENTRIO_GNSS_DRIVER_MESSAGE_RFSTATUS_H
