// Generated by gencpp from file septentrio_gnss_driver/VectorInfoGeod.msg
// DO NOT EDIT!


#ifndef SEPTENTRIO_GNSS_DRIVER_MESSAGE_VECTORINFOGEOD_H
#define SEPTENTRIO_GNSS_DRIVER_MESSAGE_VECTORINFOGEOD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace septentrio_gnss_driver
{
template <class ContainerAllocator>
struct VectorInfoGeod_
{
  typedef VectorInfoGeod_<ContainerAllocator> Type;

  VectorInfoGeod_()
    : nr_sv(0)
    , error(0)
    , mode(0)
    , misc(0)
    , delta_east(0.0)
    , delta_north(0.0)
    , delta_up(0.0)
    , delta_ve(0.0)
    , delta_vn(0.0)
    , delta_vu(0.0)
    , azimuth(0)
    , elevation(0)
    , reference_id(0)
    , corr_age(0)
    , signal_info(0)  {
    }
  VectorInfoGeod_(const ContainerAllocator& _alloc)
    : nr_sv(0)
    , error(0)
    , mode(0)
    , misc(0)
    , delta_east(0.0)
    , delta_north(0.0)
    , delta_up(0.0)
    , delta_ve(0.0)
    , delta_vn(0.0)
    , delta_vu(0.0)
    , azimuth(0)
    , elevation(0)
    , reference_id(0)
    , corr_age(0)
    , signal_info(0)  {
  (void)_alloc;
    }



   typedef uint8_t _nr_sv_type;
  _nr_sv_type nr_sv;

   typedef uint8_t _error_type;
  _error_type error;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _misc_type;
  _misc_type misc;

   typedef double _delta_east_type;
  _delta_east_type delta_east;

   typedef double _delta_north_type;
  _delta_north_type delta_north;

   typedef double _delta_up_type;
  _delta_up_type delta_up;

   typedef float _delta_ve_type;
  _delta_ve_type delta_ve;

   typedef float _delta_vn_type;
  _delta_vn_type delta_vn;

   typedef float _delta_vu_type;
  _delta_vu_type delta_vu;

   typedef uint16_t _azimuth_type;
  _azimuth_type azimuth;

   typedef int16_t _elevation_type;
  _elevation_type elevation;

   typedef uint16_t _reference_id_type;
  _reference_id_type reference_id;

   typedef uint16_t _corr_age_type;
  _corr_age_type corr_age;

   typedef uint32_t _signal_info_type;
  _signal_info_type signal_info;





  typedef boost::shared_ptr< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> const> ConstPtr;

}; // struct VectorInfoGeod_

typedef ::septentrio_gnss_driver::VectorInfoGeod_<std::allocator<void> > VectorInfoGeod;

typedef boost::shared_ptr< ::septentrio_gnss_driver::VectorInfoGeod > VectorInfoGeodPtr;
typedef boost::shared_ptr< ::septentrio_gnss_driver::VectorInfoGeod const> VectorInfoGeodConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator1> & lhs, const ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator2> & rhs)
{
  return lhs.nr_sv == rhs.nr_sv &&
    lhs.error == rhs.error &&
    lhs.mode == rhs.mode &&
    lhs.misc == rhs.misc &&
    lhs.delta_east == rhs.delta_east &&
    lhs.delta_north == rhs.delta_north &&
    lhs.delta_up == rhs.delta_up &&
    lhs.delta_ve == rhs.delta_ve &&
    lhs.delta_vn == rhs.delta_vn &&
    lhs.delta_vu == rhs.delta_vu &&
    lhs.azimuth == rhs.azimuth &&
    lhs.elevation == rhs.elevation &&
    lhs.reference_id == rhs.reference_id &&
    lhs.corr_age == rhs.corr_age &&
    lhs.signal_info == rhs.signal_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator1> & lhs, const ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace septentrio_gnss_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbd3c8ede9fdca23023a59b11ba2b072";
  }

  static const char* value(const ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdbd3c8ede9fdca23ULL;
  static const uint64_t static_value2 = 0x023a59b11ba2b072ULL;
};

template<class ContainerAllocator>
struct DataType< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> >
{
  static const char* value()
  {
    return "septentrio_gnss_driver/VectorInfoGeod";
  }

  static const char* value(const ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# VectorInfoGeod block\n"
"   \n"
"uint8   nr_sv\n"
"uint8   error\n"
"uint8   mode\n"
"uint8   misc\n"
"float64 delta_east   # m\n"
"float64 delta_north  # m\n"
"float64 delta_up     # m\n"
"float32 delta_ve     # m\n"
"float32 delta_vn     # m\n"
"float32 delta_vu     # m\n"
"uint16  azimuth      # 0.01 deg\n"
"int16   elevation    # 0.01 deg\n"
"uint16  reference_id\n"
"uint16  corr_age     # 0.01 s\n"
"uint32  signal_info\n"
;
  }

  static const char* value(const ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nr_sv);
      stream.next(m.error);
      stream.next(m.mode);
      stream.next(m.misc);
      stream.next(m.delta_east);
      stream.next(m.delta_north);
      stream.next(m.delta_up);
      stream.next(m.delta_ve);
      stream.next(m.delta_vn);
      stream.next(m.delta_vu);
      stream.next(m.azimuth);
      stream.next(m.elevation);
      stream.next(m.reference_id);
      stream.next(m.corr_age);
      stream.next(m.signal_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VectorInfoGeod_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::septentrio_gnss_driver::VectorInfoGeod_<ContainerAllocator>& v)
  {
    s << indent << "nr_sv: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.nr_sv);
    s << indent << "error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "misc: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.misc);
    s << indent << "delta_east: ";
    Printer<double>::stream(s, indent + "  ", v.delta_east);
    s << indent << "delta_north: ";
    Printer<double>::stream(s, indent + "  ", v.delta_north);
    s << indent << "delta_up: ";
    Printer<double>::stream(s, indent + "  ", v.delta_up);
    s << indent << "delta_ve: ";
    Printer<float>::stream(s, indent + "  ", v.delta_ve);
    s << indent << "delta_vn: ";
    Printer<float>::stream(s, indent + "  ", v.delta_vn);
    s << indent << "delta_vu: ";
    Printer<float>::stream(s, indent + "  ", v.delta_vu);
    s << indent << "azimuth: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.azimuth);
    s << indent << "elevation: ";
    Printer<int16_t>::stream(s, indent + "  ", v.elevation);
    s << indent << "reference_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.reference_id);
    s << indent << "corr_age: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.corr_age);
    s << indent << "signal_info: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.signal_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEPTENTRIO_GNSS_DRIVER_MESSAGE_VECTORINFOGEOD_H
