// Generated by gencpp from file septentrio_gnss_driver/VelCovGeodetic.msg
// DO NOT EDIT!


#ifndef SEPTENTRIO_GNSS_DRIVER_MESSAGE_VELCOVGEODETIC_H
#define SEPTENTRIO_GNSS_DRIVER_MESSAGE_VELCOVGEODETIC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <septentrio_gnss_driver/BlockHeader.h>

namespace septentrio_gnss_driver
{
template <class ContainerAllocator>
struct VelCovGeodetic_
{
  typedef VelCovGeodetic_<ContainerAllocator> Type;

  VelCovGeodetic_()
    : header()
    , block_header()
    , mode(0)
    , error(0)
    , cov_vnvn(0.0)
    , cov_veve(0.0)
    , cov_vuvu(0.0)
    , cov_dtdt(0.0)
    , cov_vnve(0.0)
    , cov_vnvu(0.0)
    , cov_vndt(0.0)
    , cov_vevu(0.0)
    , cov_vedt(0.0)
    , cov_vudt(0.0)  {
    }
  VelCovGeodetic_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , block_header(_alloc)
    , mode(0)
    , error(0)
    , cov_vnvn(0.0)
    , cov_veve(0.0)
    , cov_vuvu(0.0)
    , cov_dtdt(0.0)
    , cov_vnve(0.0)
    , cov_vnvu(0.0)
    , cov_vndt(0.0)
    , cov_vevu(0.0)
    , cov_vedt(0.0)
    , cov_vudt(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::septentrio_gnss_driver::BlockHeader_<ContainerAllocator>  _block_header_type;
  _block_header_type block_header;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _error_type;
  _error_type error;

   typedef float _cov_vnvn_type;
  _cov_vnvn_type cov_vnvn;

   typedef float _cov_veve_type;
  _cov_veve_type cov_veve;

   typedef float _cov_vuvu_type;
  _cov_vuvu_type cov_vuvu;

   typedef float _cov_dtdt_type;
  _cov_dtdt_type cov_dtdt;

   typedef float _cov_vnve_type;
  _cov_vnve_type cov_vnve;

   typedef float _cov_vnvu_type;
  _cov_vnvu_type cov_vnvu;

   typedef float _cov_vndt_type;
  _cov_vndt_type cov_vndt;

   typedef float _cov_vevu_type;
  _cov_vevu_type cov_vevu;

   typedef float _cov_vedt_type;
  _cov_vedt_type cov_vedt;

   typedef float _cov_vudt_type;
  _cov_vudt_type cov_vudt;





  typedef boost::shared_ptr< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> const> ConstPtr;

}; // struct VelCovGeodetic_

typedef ::septentrio_gnss_driver::VelCovGeodetic_<std::allocator<void> > VelCovGeodetic;

typedef boost::shared_ptr< ::septentrio_gnss_driver::VelCovGeodetic > VelCovGeodeticPtr;
typedef boost::shared_ptr< ::septentrio_gnss_driver::VelCovGeodetic const> VelCovGeodeticConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator1> & lhs, const ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.block_header == rhs.block_header &&
    lhs.mode == rhs.mode &&
    lhs.error == rhs.error &&
    lhs.cov_vnvn == rhs.cov_vnvn &&
    lhs.cov_veve == rhs.cov_veve &&
    lhs.cov_vuvu == rhs.cov_vuvu &&
    lhs.cov_dtdt == rhs.cov_dtdt &&
    lhs.cov_vnve == rhs.cov_vnve &&
    lhs.cov_vnvu == rhs.cov_vnvu &&
    lhs.cov_vndt == rhs.cov_vndt &&
    lhs.cov_vevu == rhs.cov_vevu &&
    lhs.cov_vedt == rhs.cov_vedt &&
    lhs.cov_vudt == rhs.cov_vudt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator1> & lhs, const ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace septentrio_gnss_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b62aa4ae504c44f18ac72015246a1586";
  }

  static const char* value(const ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb62aa4ae504c44f1ULL;
  static const uint64_t static_value2 = 0x8ac72015246a1586ULL;
};

template<class ContainerAllocator>
struct DataType< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "septentrio_gnss_driver/VelCovGeodetic";
  }

  static const char* value(const ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# VelCovGeodetic block\n"
"# ROS message header\n"
"std_msgs/Header header\n"
"\n"
"# SBF block header including time header\n"
"BlockHeader  block_header   \n"
"\n"
"uint8        mode\n"
"uint8        error        \n"
"float32      cov_vnvn # m^2/s^2\n"
"float32      cov_veve # m^2/s^2\n"
"float32      cov_vuvu # m^2/s^2\n"
"float32      cov_dtdt # m^2/s^2\n"
"float32      cov_vnve # m^2/s^2\n"
"float32      cov_vnvu # m^2/s^2\n"
"float32      cov_vndt # m^2/s^2\n"
"float32      cov_vevu # m^2/s^2\n"
"float32      cov_vedt # m^2/s^2\n"
"float32      cov_vudt # m^2/s^2\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: septentrio_gnss_driver/BlockHeader\n"
"# Blockheader including time header for all ROS messages that publish SBF blocks\n"
"\n"
"uint8     sync_1\n"
"uint8     sync_2\n"
"uint16    crc\n"
"uint16    id\n"
"uint8     revision\n"
"uint16    length\n"
"\n"
"uint32    tow # ms since week start\n"
"uint16    wnc # weeks since Jan 06, 1980 at 00:00:00 UTC     \n"
;
  }

  static const char* value(const ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.block_header);
      stream.next(m.mode);
      stream.next(m.error);
      stream.next(m.cov_vnvn);
      stream.next(m.cov_veve);
      stream.next(m.cov_vuvu);
      stream.next(m.cov_dtdt);
      stream.next(m.cov_vnve);
      stream.next(m.cov_vnvu);
      stream.next(m.cov_vndt);
      stream.next(m.cov_vevu);
      stream.next(m.cov_vedt);
      stream.next(m.cov_vudt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelCovGeodetic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::septentrio_gnss_driver::VelCovGeodetic_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "block_header: ";
    s << std::endl;
    Printer< ::septentrio_gnss_driver::BlockHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.block_header);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error);
    s << indent << "cov_vnvn: ";
    Printer<float>::stream(s, indent + "  ", v.cov_vnvn);
    s << indent << "cov_veve: ";
    Printer<float>::stream(s, indent + "  ", v.cov_veve);
    s << indent << "cov_vuvu: ";
    Printer<float>::stream(s, indent + "  ", v.cov_vuvu);
    s << indent << "cov_dtdt: ";
    Printer<float>::stream(s, indent + "  ", v.cov_dtdt);
    s << indent << "cov_vnve: ";
    Printer<float>::stream(s, indent + "  ", v.cov_vnve);
    s << indent << "cov_vnvu: ";
    Printer<float>::stream(s, indent + "  ", v.cov_vnvu);
    s << indent << "cov_vndt: ";
    Printer<float>::stream(s, indent + "  ", v.cov_vndt);
    s << indent << "cov_vevu: ";
    Printer<float>::stream(s, indent + "  ", v.cov_vevu);
    s << indent << "cov_vedt: ";
    Printer<float>::stream(s, indent + "  ", v.cov_vedt);
    s << indent << "cov_vudt: ";
    Printer<float>::stream(s, indent + "  ", v.cov_vudt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEPTENTRIO_GNSS_DRIVER_MESSAGE_VELCOVGEODETIC_H
